/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Registration } from "./Registration";
import { RegistrationCountArgs } from "./RegistrationCountArgs";
import { RegistrationFindManyArgs } from "./RegistrationFindManyArgs";
import { RegistrationFindUniqueArgs } from "./RegistrationFindUniqueArgs";
import { DeleteRegistrationArgs } from "./DeleteRegistrationArgs";
import { RegistrationService } from "../registration.service";
@graphql.Resolver(() => Registration)
export class RegistrationResolverBase {
  constructor(protected readonly service: RegistrationService) {}

  async _registrationsMeta(
    @graphql.Args() args: RegistrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Registration])
  async registrations(
    @graphql.Args() args: RegistrationFindManyArgs
  ): Promise<Registration[]> {
    return this.service.registrations(args);
  }

  @graphql.Query(() => Registration, { nullable: true })
  async registration(
    @graphql.Args() args: RegistrationFindUniqueArgs
  ): Promise<Registration | null> {
    const result = await this.service.registration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Registration)
  async deleteRegistration(
    @graphql.Args() args: DeleteRegistrationArgs
  ): Promise<Registration | null> {
    try {
      return await this.service.deleteRegistration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
